# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tb.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08tb.proto\"\'\n\x0b\x41\x64\x64Operands\x12\x0b\n\x03ina\x18\x01 \x01(\x05\x12\x0b\n\x03inb\x18\x02 \x01(\x05\"\x18\n\tAddResult\x12\x0b\n\x03res\x18\x01 \x01(\x05\x32/\n\nAddNumbers\x12!\n\x03\x41\x64\x64\x12\x0c.AddOperands\x1a\n.AddResult\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tb_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ADDOPERANDS._serialized_start=12
  _ADDOPERANDS._serialized_end=51
  _ADDRESULT._serialized_start=53
  _ADDRESULT._serialized_end=77
  _ADDNUMBERS._serialized_start=79
  _ADDNUMBERS._serialized_end=126
# @@protoc_insertion_point(module_scope)
